name: 沙中世界
title: 沙中世界 | 随笔记录
description: IT圈中的一粒沙，也是一个世界
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: 806801463@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: mzbnoqlo
